version: "3.7"

services:
  db:
    image: mysql:8.0.37
    restart: always
    volumes:
      - chatapp-db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chatapp
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  redis:
    image: redis/redis-stack-server:7.2.0-v10
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 20s
      retries: 10
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "CMD", "curl", "-f", "-s-", "http://es01:9200", "||", "exit", "1"
        ]
      timeout: 20s
      retries: 10

  sidekiq:
    build: .
    command: bundle exec sidekiq --environment development -C config/sidekiq.yml
    environment:
      REDIS_URL: "redis://redis:6379/1"
      DB_HOST: db
      DB_PORT: 3306
      ELASTICSEARCH_URL: "http://es01:9200"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
      - web
      - es01

  web:
    build: .
    restart: always
    command: bash -c "bundle exec rake db:migrate && ./bin/rails searchkick:reindex CLASS=Message && ./bin/rails server --binding 0.0.0.0 -e development"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 123456
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_URL: "redis://redis:6379/1"
      ELASTICSEARCH_URL: "http://es01:9200"
      DB_PORT: 3306
      DB_HOST: db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      timeout: 20s
      retries: 10
    volumes:
      - ../:/rails-app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - es01
volumes:
  chatapp-db:
  redis:
  esdata01:
  bundle: